CREATE DATABASE IF NOT EXISTS dashboard;
USE dashboard;
CREATE TABLE users(
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(25) DEFAULT NULL,
    email VARCHAR(25) DEFAULT NULL,
    password VARCHAR(25) DEFAULT NULL,
    register DATE DEFAULT NULL,
    lastlogin DATE DEFAULT NULL
);
